version: '3.7'

services:
  scala-sbt:
    build:
      context: ./scala-sbt
      dockerfile: Dockerfile
    command: bash -c "cd /usr/app/ && sbt ~testQuick"
    container_name: scala-sbt
    env_file:
      - ../.env/development.env
    tty: true
    volumes:
      - ../:/usr/app/
